# Use the Windows Server Core as the base image
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

# Set the working directory inside the container
WORKDIR /app

# Copy the application files from the host to the container
COPY bin/Debug/net8.0-windows/ .

# Command to run the Windows Forms app
CMD ["HelloWorldWinApp.exe"]            
